<main id="chat">
    <?php require "templates/partials/_aside.phtml"; ?>
    <ul>
        <h2>Channel 1</h2>
        <li>
            <article>
                <header>
                    <figure>
                        <img src="https://picsum.photos/20" alt=""/>
                    </figure>
                    <p>Auteur du message</p>
                </header>
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                    Ab architecto consequuntur doloremque inventore iste laborum magnam magni,
                    odio quibusdam quis quod saepe sapiente voluptatum. Dolores ex fuga incidunt recusandae soluta.
                </p>
                <footer>
                    <p>
                        Date et heure du message
                    </p>
                </footer>
            </article>
        </li>
        <li>
            <article>
                <header>
                    <figure>
                        <img src="https://picsum.photos/20" alt=""/>
                    </figure>
                    <p>Auteur du message</p>
                </header>
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                    Ab architecto consequuntur doloremque inventore iste laborum magnam magni.
                </p>
                <footer>
                    <p>
                        Date et heure du message
                    </p>
                </footer>
            </article>
        </li>
        <li>
            <article>
                <header>
                    <figure>
                        <img src="https://picsum.photos/20" alt=""/>
                    </figure>
                    <p>Auteur du message</p>
                </header>
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                    Ab architecto consequuntur doloremque inventore iste laborum magnam magni,
                    odio quibusdam quis quod saepe sapiente voluptatum. Dolores ex fuga incidunt recusandae soluta.
                </p>
                <footer>
                    <p>
                        Date et heure du message
                    </p>
                </footer>
            </article>
        </li>
        <li>
            <article>
                <header>
                    <figure>
                        <img src="https://picsum.photos/20" alt=""/>
                    </figure>
                    <p>Auteur du message</p>
                </header>
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                    Ab architecto consequuntur doloremque inventore iste laborum magnam magni.
                </p>
                <footer>
                    <p>
                        Date et heure du message
                    </p>
                </footer>
            </article>
        </li>
        <li>
            <article>
                <header>
                    <figure>
                        <img src="https://picsum.photos/20" alt=""/>
                    </figure>
                    <p>Auteur du message</p>
                </header>
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                    Ab architecto consequuntur doloremque inventore iste laborum magnam magni,
                    odio quibusdam quis quod saepe sapiente voluptatum. Dolores ex fuga incidunt recusandae soluta.
                </p>
                <footer>
                    <p>
                        Date et heure du message
                    </p>
                </footer>
            </article>
        </li>
        <li>
            <article>
                <header>
                    <figure>
                        <img src="https://picsum.photos/20" alt=""/>
                    </figure>
                    <p>Auteur du message</p>
                </header>
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                    Ab architecto consequuntur doloremque inventore iste laborum magnam magni.
                </p>
                <footer>
                    <p>
                        Date et heure du message
                    </p>
                </footer>
            </article>
        </li>
    </ul>
    <form id="send-message">
        <input type="hidden" id="chan-id" name="chan-id" value="" />
        <textarea id="message" name="message" aria-label="Your message">

        </textarea>
        <button type="submit" aria-label="Send Message"><span class="bi bi-send"></span></button>
    </form>
</main>